config/routes.rb
Creatishop::Application.routes.draw do
  get "checkout/product_purchase"
  get "checkout/payment"
  get "checkout/cart"
  get "shopping/product_display"
  get "shopping/shop"

  get 'rails-admin', to: 'admin/dashboard#show'
  get "admin/dashboard/index"

  get 'download_file/:id' => "admin/products#download_file", as: "download_file"

   get "admin/managers/edit"
   get "admin/managers/new"
   post "admin/managers/update"

   get "admin/sessions/login"
   get "admin/sessions/logout"
   post "admin/sessions/login_attempt"

   get "admin/products/index"
   get "admin/products/new"
   get "admin/products/edit"
   get "admin/products/show"
   get "admin/products/delete"
   post "admin/products/create"
   post "admin/products/update"
   post "admin/products/multiple_remove"
  resources :charges, :only => :create

  root 'landing#land'

   scope module: 'admin' do
      resources :dashboard, :managers, :sessions, :products
    end
   namespace :admin do 
      get '', to: 'dashboard#index', as: '/'       
      resources :dashboard
   end 
end

app/views/layouts/admin/_admin_alert.html.erb
<% if notice %>
  <div class="alert alert-error">
     <button class="close" data-dismiss="alert"></button>
     <%= raw notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-success">
      <button class="close" data-dismiss="alert"></button>
      <%= raw alert %>
 </div>  
<% end %>

app/views/layouts/admin/_admin_footer.html.erb
 <!-- BEGIN FOOTER -->
  <div class="footer">
    2013 &copy; Metronic by keenthemes.
    <div class="span pull-right">
      <span class="go-top"><i class="icon-angle-up"></i></span>
    </div>
  </div>
  <!-- END FOOTER -->

app/views/layouts/admin/_admin_menu.html.erb
<!-- BEGIN SIDEBAR -->
   <%
    if params[:controller].split("/").last == "products"
      pro = "active"
    elsif params[:controller].split("/").last == "dashboard" 
      dash = "active"
    elsif params[:controller] == "admin/managers" && params[:action] == "new"
      new_user = "active"
    end
   %>
    <div class="page-sidebar nav-collapse collapse">
      <!-- BEGIN SIDEBAR MENU -->         
      <ul>
        <li>
          <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
          <div class="sidebar-toggler hidden-phone"></div>
          <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
        </li>
        <li>
          <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
          <form class="sidebar-search">
            <div class="input-box">
              <a href="javascript:;" class="remove"></a>
              <input type="text" placeholder="Search..." />       
              <input type="button" class="submit" value=" " />
            </div>
          </form>
          <!-- END RESPONSIVE QUICK SEARCH FORM -->
        </li>
        <li class="<%= dash %> ">
           <%= link_to 'Dashboard', :controller => :dashboard, :action => :show %>          
        </li>        
        <li class="<%= pro %>">
         <%= link_to 'Products', :controller => :products, :action => :index %>   
        </li> 
        <li class="<%= new_user %>">
         <%= link_to 'Add User', admin_managers_new_path %>   
        </li> 
          
         
      </ul>
      <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->

app/views/layouts/admin/_admin_stylesheets.html.erb
<%= stylesheet_link_tag "admin/bootstrap/css/bootstrap.min" %>
<%= stylesheet_link_tag "admin/css/metro" %>


<%= stylesheet_link_tag "admin/bootstrap/css/bootstrap-responsive.min" %>
<%= stylesheet_link_tag "admin/font-awesome/css/font-awesome" %>
<%= stylesheet_link_tag "admin/css/style" %>
<%= stylesheet_link_tag "admin/css/style_responsive" %>
<%= stylesheet_link_tag "admin/css/style_default" %>
<%= stylesheet_link_tag "admin/fullcalendar/fullcalendar/bootstrap-fullcalendar" %>
<%= stylesheet_link_tag "admin/chosen-bootstrap/chosen/chosen" %>
<%= stylesheet_link_tag "admin/uniform/css/uniform.default.css" %>
<%= stylesheet_link_tag "admin/data-tables/DT_bootstrap" %>
<%= stylesheet_link_tag "admin/fancybox/source/jquery.fancybox.chosen-bootstrap" %>  
 

app/views/layouts/admin/_admin_top.html.erb
<!-- BEGIN HEADER -->
  <div class="header navbar navbar-inverse navbar-fixed-top">
    <!-- BEGIN TOP NAVIGATION BAR -->
    <div class="navbar-inner">
      <div class="container-fluid">
        <!-- BEGIN LOGO -->
        <a class="brand" href="index.html">
        <img src="assets/img/logo.png" alt="logo" />
        </a>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
        <img src="assets/img/menu-toggler.png" alt="" />
        </a>          
        <!-- END RESPONSIVE MENU TOGGLER -->        
        <!-- BEGIN TOP NAVIGATION MENU -->          
        <ul class="nav pull-right">
         <li class="dropdown user open">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img alt="" src="assets/img/avatar1_small.jpg">
            <span class="username">Bob Nilson</span>
            <i class="icon-angle-down"></i>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to admin_managers_edit_path do %>
                   <i class="icon-user"></i>  My Profile 
              <% end %>
              </li>
              
              
              <li>
                <%= link_to admin_sessions_logout_path do %>
                   <i class="icon-key"></i>  Log Out 
              <% end %>
              </li>

            </ul>
          </li>
         
        </ul>
        <!-- END TOP NAVIGATION MENU -->  
      </div>
    </div>
    <!-- END TOP NAVIGATION BAR -->
  </div>
  <!-- END HEADER -->

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
  <meta charset="utf-8" />
  <title>CreatiShop | Admin</title>
  <%= csrf_meta_tag %>

  <%= render 'layouts/admin/admin_stylesheets' %>
 
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="fixed-top">
   <%= render 'layouts/admin/admin_top' %>
  <!-- BEGIN CONTAINER -->  
  <div class="page-container row-fluid">
    <%= render 'layouts/admin/admin_menu' %>
    
    <!-- BEGIN PAGE -->
    <div class="page-content">
    
      <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
      <div id="portlet-config" class="modal hide">
        <div class="modal-header">
          <button data-dismiss="modal" class="close" type="button"></button>
          <h3>portlet Settings</h3>
        </div>
        <div class="modal-body">
          <p>Here will be a configuration form</p>
        </div>
      </div>
      <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
      <!-- BEGIN PAGE CONTAINER-->
      <div class="container-fluid">                   
          <%= yield %>        
      </div>
      <!-- END PAGE CONTAINER-->  
    </div>
    <!-- END PAGE -->   
  </div>
  <!-- END CONTAINER -->
  <!-- BEGIN FOOTER -->
   <%= render 'layouts/admin/admin_footer' %>
  <!-- END FOOTER -->
  <!-- BEGIN JAVASCRIPTS -->
  <!-- Load javascripts at bottom, this will reduce page load time -->
<%= javascript_include_tag "admin/js/jquery-1.8.3.min" %>
<%= javascript_include_tag "admin/breakpoints/breakpoints" %>
<%= javascript_include_tag "admin/jquery-slimscroll/jquery-ui-1.9.2.custom.min" %>
<%= javascript_include_tag "admin/bootstrap/js/bootstrap.min" %>
<%= javascript_include_tag "admin/js/jquery.blockui" %>
<%= javascript_include_tag "admin/js/jquery.cookie" %>
<%= javascript_include_tag "admin/fullcalendar/fullcalendar/fullcalendar" %>
<%= javascript_include_tag "admin/uniform/jquery.uniform.min" %>
<%= javascript_include_tag "admin/chosen-bootstrap/chosen/chosen.jquery.min" %>
<%= javascript_include_tag "admin/data-tables/jquery.dataTables" %>
<%= javascript_include_tag "admin/data-tables/DT_bootstrap" %>
<%= javascript_include_tag "admin/ckeditor/ckeditor" %>




  
  <!-- ie8 fixes -->
  <!--[if lt IE 9]>
  <script src="assets/js/excanvas.js"></script>
  <script src="assets/js/respond.js"></script>
  <![endif]-->
  <%= javascript_include_tag "admin/js/app" %> 
  <script>
    jQuery(document).ready(function() {     
      // initiate layout and plugins
      App.setPage('table_managed');
      App.init();
    });
  </script>
  <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
  <meta charset="utf-8" />
  <title>Admin Login</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <%= render 'layouts/admin/admin_stylesheets' %>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
  <!-- BEGIN LOGO -->
  <div class="logo">
    <img src="assets/img/logo-big.png" alt="" /> 
  </div>
  <!-- END LOGO -->
 <%= yield %>
  <!-- END LOGIN -->
  <!-- BEGIN COPYRIGHT -->
  <div class="copyright">
    <!-- BEGIN FOOTER -->
   <%= render 'layouts/admin/admin_footer' %>
  <!-- END FOOTER -->
  </div>
  <!-- END COPYRIGHT -->
  <!-- BEGIN JAVASCRIPTS -->

  <%= javascript_include_tag "admin/js/jquery-1.8.3.min" %>
  <%= javascript_include_tag "admin/bootstrap/js/bootstrap.min" %>
  <%= javascript_include_tag "admin/uniform/jquery.uniform.min" %>
  <%= javascript_include_tag "admin/js/jquery.blockui" %>
  <%= javascript_include_tag "admin/jquery-validation/dist/jquery.validate.min" %>
  <%= javascript_include_tag "admin/js/jquery-1.8.3.min" %>
  <%= javascript_include_tag "admin/js/app" %>
  <script>
    jQuery(document).ready(function() {     
      App.initLogin();
    });
  </script>
  <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>