config/routes.rb
Creatishop::Application.routes.draw do
  get "checkout/product_purchase"
  get "checkout/payment"
  get "checkout/cart"
  get "shopping/product_display"
  get "shopping/shop"

  get 'rails-admin', to: 'admin/dashboard#show'
  get "admin/dashboard/index"

  get 'download_file/:id' => "admin/products#download_file", as: "download_file"

   get "admin/managers/edit"
   get "admin/managers/new"
   post "admin/managers/update"

   get "admin/sessions/login"
   get "admin/sessions/logout"
   post "admin/sessions/login_attempt"

   get "admin/products/index"
   get "admin/products/new"
   get "admin/products/edit"
   get "admin/products/show"
   get "admin/products/delete"
   post "admin/products/create"
   post "admin/products/update"
   post "admin/products/multiple_remove"
  resources :charges, :only => :create

  root 'landing#land'

   scope module: 'admin' do
      resources :dashboard, :managers, :sessions, :products
    end
   namespace :admin do 
      get '', to: 'dashboard#index', as: '/'       
      resources :dashboard
   end 
end

app/models/admin/product.rb
class Admin::Product < ActiveRecord::Base
   self.table_name = "admin_products"
  
   validates :name, :presence => true , :length => { :maximum => 50 }
   validates :description, :presence => true
   validates :price, :presence => true , :length => { :maximum => 50 }
   validates :price, :numericality => true, :allow_nil => false  
   validates :height, :presence => true , :length => { :maximum => 50 }
   validates :height, :numericality => true, :allow_nil => false  
   validates :weight, :presence => true , :length => { :maximum => 50 }
   validates :weight, :numericality => true, :allow_nil => false  
   validates :stem, :presence => true , :length => { :maximum => 50 }
   validates :artist, :presence => true , :length => { :maximum => 50 }
   validates :p_image, :presence => true  
   validates :p_image, allow_blank: false, format: { with: %r{\.gif|jpg|png|mp3|epub}i, message: 'must be a gif, jpg, png, mp3 or epub format.'}

   def self.payment(amount,stripe_token )
      customer = Stripe::Customer.create(
          :card  => stripe_token
         )
      binding.pry
         charge = Stripe::Charge.create(
          :customer    => customer.id,
          :amount      => amount,
          :description => 'Stripe payment for $3',
          :currency    => 'usd'
        )
      rescue Stripe::CardError => e
   end



end

app/models/product.rb
class Product < ActiveRecord::Base
   self.table_name = "admin_products"
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	layout 'admin/admin'
	before_filter :authenticate_user

	def index
		@products = Admin::Product.all
		@model = Admin::Product.new
	end

	def show
		@product = Admin::Product.find_by_id(params[:id])	
	end

	def new
		@product = Admin::Product.new
		@action = 'create'
	end

	def create
		@action = 'create'
	    #@Product = Admin::Product.new(:name => params[:Product][:name],:catagory => params[:Product][:catagory], :flower => params[:Product][:flower])
	    @product = Admin::Product.new
	    
	    #### IMAGE UPLOAD START   ############
        upload = params[:product][:p_image]

        if upload
	        @time = Time.now.to_i
		    @strng_time = @time.to_s     
		    flower_name =   @strng_time.split(//).last(4).join("").to_s + upload.original_filename
		    directory = "app/assets/images/uploads/products"
		    # create the file path
		    path = File.join(directory, flower_name) 
		    @product.p_image = flower_name
		end
	    #### IMAGE UPLOAD BREAK ONE   ############	    
        @product.name = params[:product][:name]
        @product.height = params[:product][:height]
        @product.description = params[:product][:description]
        @product.price = params[:product][:price]
        @product.weight = params[:product][:weight]
        @product.stem = params[:product][:stem]
        @product.artist = params[:product][:artist]
        

	    if @product.save
	      #### IMAGE UPLOAD RESTART BREAK ONE   ############
	      # write the file
	      if upload
	      	File.open(path, "wb") { |f| f.write(upload.read) }
	      end	
	      #### IMAGE UPLOAD START END   ############     
	     
	      redirect_to products_path, :flash => { :alert => "Products Successfully Saved" }	      
	    else
	     flash[:notice] = "Product cannot save"
	     render 'new'
	    end
  end

	def edit
		@action = 'update'
		@product = Admin::Product.find(params[:id])
	end

	def update
		@action = 'update'	
		@old_Product = Admin::Product.find_by_id(params[:id])	
		@product = Admin::Product.find_by_id(params[:id])
		@p_image = @product.p_image
		#### IMAGE UPLOAD START   ############
        upload = params[:product][:p_image]
        if upload
	        @time = Time.now.to_i
		    @strng_time = @time.to_s     
		    flower_name =   @strng_time.split(//).last(4).join("").to_s + upload.original_filename
		    directory = "app/assets/images/uploads/products"
		    # create the file path
		    path = File.join(directory, flower_name) 
		    @product.p_image = flower_name
		end
	    #### IMAGE UPLOAD BREAK ONE   ############

		@product.name = params[:product][:name]
        @product.catagory = params[:product][:height]
        @product.description = params[:product][:description]
        @product.price = params[:product][:price]
        @product.weight = params[:product][:weight]
        @product.stem = params[:product][:stem]
        @product.artist = params[:product][:artist]
        #@obj = Admin::Product.update(@Product.id, :name => params[:Product][:name], :catagory => params[:Product][:catagory], :flower => @flower)
        if @product.save
        	if upload
	      		File.open(path, "wb") { |f| f.write(upload.read) }
	      	    #Delete the old one
	      		img_url = Rails.root.join('app', 'assets', 'images', 'uploads', 'products', @old_Product.p_image)
	      		if File.exist?(img_url)
                	File.delete(img_url) 
            	end
            	   


	        end
	        flash[:alert] = "Product Updated Successfully."
	        redirect_to(:controller => 'products', :action => 'index')
        else        
        	render 'edit'

        end
	end

	def delete	   
	   @content = Admin::Product.find(params[:id])
	   img_url = Rails.root.join('app', 'assets', 'images', 'uploads', 'products', @content.p_image)
	   if File.exist?(img_url)
          File.delete(img_url) 
       end
       @content.destroy
       flash[:alert] = "Product Deleted Successfully."
       redirect_to(:controller => 'products', :action => 'index')
	end

	def multiple_remove	   
	   if request.post?
	   	 @ids = params[:ids]

	   	 if @ids
	   	 	@ids.each do |id| 
	   	 		@prod = Admin::Product.find_by_id(id)
	   	 		img_url = Rails.root.join('app', 'assets', 'images', 'uploads', 'products', @prod.p_image)
				if File.exist?(img_url)
			        File.delete(img_url) 
			     end	   	 		
	   	 		@prod.destroy	   	 		
	   	    end
	   	    flash[:alert] = "Product Deleted Successfully."
	        redirect_to(:controller => 'products', :action => 'index')
	   	 else
	   	 	flash[:notice] = "Please choose a Product to delete."
	        redirect_to(:controller => 'products', :action => 'index')
	   	 end
	   else	   	  
	   	  redirect_to(:controller => 'products', :action => 'index')
	   end
	end

	def download_file
		product = Admin::Product.find(params[:id])
		extension = File.extname(product.p_image).gsub(".", "")
    send_file "#{Rails.root}/app/assets/images/uploads/products/#{product.p_image}", :type=>"application/#{extension}", :x_sendfile=>true
	end

	private

	  def product_params
	    params.require(:product).permit(:catagory, :name, :p_image)
	  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_error_messages.html.erb
<% if flowerad.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(flowerad.errors.count, "error") %> 
        prohibited this <%= flowerad.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% flowerad.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/products/_form.html.erb
 
  <% if @product.errors.full_messages.any? %>
         <div class="alert alert-error">
         <p><strong>Please fix the following input Errors: </strong></p>
            <% @product.errors.full_messages.each do |error_message| %>
            <li> <%= error_message %></li>
            <% end %>
         </div> 
     <% end %>

<!-- BEGIN FORM-->
<%= form_for(:product, :url => {:controller => 'products', :action => @action }, :html=> { class: 'form-horizontal', :multipart => true }) do |f| %>
                         

                
            <% if @action == "update"  %>   
              <%= hidden_field_tag "id", @product.id %>   
            <% end %> 
                           <div class="control-group">
                              <label class="control-label"> Name <font color="red">*</font></label>
                              <div class="controls">                                 
                                  <%= f.text_field :name, :class => 'medium span6 m-wrap' %>
                                 <span class="help-inline"></span>
                              </div>
                           </div>

                           <div class="control-group">
                              <label class="control-label">Artist <font color="red">*</font></label>
                              <div class="controls">                                
                              <%= f.text_field :artist, :class => 'medium span6 m-wrap' %>
                                 <span class="help-inline"></span>
                              </div>
                           </div>
                           <div class="control-group">
                              <label class="control-label">Price <font color="red">*</font></label>
                              <div class="controls">
                                 <%= f.text_field :price, :class => 'medium span6 m-wrap' %>
                                 <span class="help-inline"></span>
                              </div>
                           </div>
                           <div class="control-group">
                              <label class="control-label">Height <font color="red">*</font></label>                              
                              <div class="controls">                            
                                   <%= f.text_field :height, :class => 'medium span6 m-wrap' %>
                                 <span class="help-inline"></span>
                              </div>
                           </div>
                           <div class="control-group">
                              <label class="control-label">Weight <font color="red">*</font></label>                              
                              <div class="controls">                            
                                   <%= f.text_field :weight, :class => 'medium span6 m-wrap' %>
                                 <span class="help-inline"></span>
                              </div>
                           </div>
                           <div class="control-group">
                              <label class="control-label">Stem <font color="red">*</font></label>                              
                              <div class="controls">                            
                                   <%= f.text_field :stem, :class => 'medium span6 m-wrap' %>
                                 <span class="help-inline"></span>
                              </div>
                           </div>
                           <div class="control-group">
                              <label class="control-label">Description <font color="red">*</font></label>
                              <div class="controls">
                                <%= f.text_area :description, :rows => "6", :class => 'span12 ckeditor m-wrap' %>                               
                                 <span class="help-inline"></span>
                              </div>
                           </div>

                           <div class="control-group">
                              <label class="control-label">Image <font color="red">*</font></label>
                              <div class="controls">
                                 <%= f.file_field :p_image %>
                              <%
                              if @action == "update"
                              %>
                              <span class="help-inline"><%= image_tag("uploads/products/" + @product.p_image, height: '100', width: '100') %>
                            <% end %>
                                </span>
                              </div>
                           </div>    
                           
                           <div class="form-actions">
                              <%= f.submit :Save, :class=> 'btn blue'  %>                                
                              <%= link_to "Cancel", admin_products_index_path, :class => "btn"  %>
									 
							          
                           </div>
                        <% end %>
                        <!-- END FORM--> 
                       
                      
      

app/views/admin/products/_product_attachment.html.erb
<%= image_tag("#{type}.png", height: height, width: width) %><br/>
<%= link_to product.p_image, download_file_path(product) %>

app/views/admin/products/aaaaaaaaaa.html.erb
<%= @id.inspect %>

app/views/admin/products/edit.html.erb
<!-- BEGIN PAGE HEADER-->
<div class="row-fluid">
    <div class="span12"> 
		<!-- BEGIN PAGE TITLE & BREADCRUMB-->     
		<h3 class="page-title"> Products  </h3>
		<ul class="breadcrumb">
		    <li>
      <%= link_to admin_dashboard_index_path, :id => "sample_editable_1_new" do %>
          Home <i class="icon-home"></i>
        <% end %>

    </li>
		</ul>
		 <!-- END PAGE TITLE & BREADCRUMB-->
     </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row-fluid">
    <div class="span12">
         <!-- BEGIN SAMPLE FORM PORTLET-->   
                  <div class="portlet box blue">
                     <div class="portlet-title">
                        <h4><i class="icon-reorder"></i>Edit Product</h4>
                        <div class="tools">
                           <a href="javascript:;" class="collapse"></a>
                           <a href="#portlet-config" data-toggle="modal" class="config"></a>
                           <a href="javascript:;" class="reload"></a>
                           <a href="javascript:;" class="remove"></a>
                        </div>
                     </div>
                     <div class="portlet-body form">
                        <%= render 'layouts/admin/admin_alert' %>
                        <%= render 'admin/products/form' %>                                 
                     </div>
                  </div>
                  <!-- END SAMPLE FORM PORTLET-->   
    </div>
</div>
        <!-- END PAGE CONTENT-->

app/views/admin/products/index.html.erb
<script type="text/javascript">
//checkbox multiple select option
function select_all() {
	var dt = jQuery('#sample_2').dataTable();
	var chk;
	if(jQuery('#selectall_val').val() == 1 ){
	   jQuery('#selectall_val').val(0);
	   chk =jQuery("#ids_", dt.fnGetNodes()).attr("checked", false);
	}else{
	   jQuery('#selectall_val').val(1);
	   chk =jQuery("#ids_", dt.fnGetNodes()).attr("checked", true);
	}
	jQuery.uniform.update(chk);

}

function multiple(){
  if(confirm('Are you sure you want to delete')){
     jQuery('#list-sk').submit();
  }else{
     return false;
  }
}
</script>
<div class="row-fluid">
    <div class="span12"> 
		<!-- BEGIN PAGE TITLE & BREADCRUMB-->     
		<h3 class="page-title"> Products </h3>
		<ul class="breadcrumb">
		    <li>
			<%= link_to admin_dashboard_index_path, :id => "sample_editable_1_new" do %>
			    Home <i class="icon-home"></i>
		    <% end %>

		</li>
		</ul>
		 <!-- END PAGE TITLE & BREADCRUMB-->
     </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row-fluid">
    <div class="span12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
						<div class="portlet box blue">
							<div class="portlet-title">
								<h4><i class="icon-globe"></i>Products </h4>								
							</div>
							<div class="portlet-body">
								<div class="clearfix">
									<div class="btn-group">
									
									   <%= link_to admin_products_new_path, :id => "sample_editable_1_new", :class => "btn blue" do %>
									   		Add Products <i class="icon-plus"></i>
									   <% end %>   
										
									</div>
									<div class="btn-group pull-right">
										<button class="btn dropdown-toggle red" data-toggle="dropdown">Bulk Delete <i class="icon-trash"></i>
										</button>
										<ul class="dropdown-menu">
											<li><a href="#" onclick="multiple();">Delete</a></li>											
										</ul>
									</div>
								</div>
                               	
                              <input type="hidden" id="selectall_val" value="0" />
                               <%= render 'layouts/admin/admin_alert' %>
                               <%= form_for(:model, :url => {:action => 'multiple_remove'}, :html=> { id: 'list-sk' }) do |f| %>
                                <table class="table table-striped table-bordered table-hover" id="sample_2">
									<thead>
										<tr>
											<th style="width:8px;"><input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" id="selectall" onclick="select_all();"/></th>
											<th>Product Name</th>
											<th>Product Attachment</th>
											<th>Artist</th>
											<th>Price</th>
																				
											<th ></th>
										</tr>
									</thead>
									<tbody>
									<% @products.each do |product| %>
										<tr class="odd gradeX">
											<td>
												 <%= check_box_tag 'ids[]', product.id %>
											</td>
                                               
											<td><%= product.name %></td>
											<td>
												<% if File.extname(product.p_image) != ".mp3" && File.extname(product.p_image) != ".epub" %>
												<%= image_tag("uploads/products/" + product.p_image, height: '100', width: '100') %>
												<% elsif File.extname(product.p_image) == ".mp3" %>
													<%= render 'product_attachment', product: product, type: "music", height: "100", width: "100" %>
												<% else %>
													<%= render 'product_attachment', product: product, type: "file", height: "100" , width: "50" %>
												<% end %>
											</td>	
											<td><%= product.artist %></td>
											<td><%= product.price %></td>
																				
											<td >
							 <%= social_share_button_tag(product.name, :popup => "true", :url => admin_products_show_url(id: product.id) ) %>               
							 <%= link_to admin_products_show_path(id: product.id), :id => "sample_editable_1_new", :class => "btn mini blue" do %>
									   		View Product  <i class="icon-edit"></i>
							  <% end %>

							   <%= link_to admin_products_edit_path(id: product.id), :id => "sample_editable_1_new", :class => "btn mini green" do %>
									   		Edit Product  <i class="icon-edit"></i>
							  <% end %>
							   <%= link_to admin_products_delete_path(id: product.id), :id => "sample_editable_1_new", :class => "btn mini red", :onclick => "delte" do %>
									   		Delete Product  <i class="icon-trash"></i>
							  <% end %>
							  
									   				 												
											</td>
										</tr>
									<% end %>											
									</tbody>
								</table>
                              
								<% end %>

							</div>
						</div>
						<!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
        <!-- END PAGE CONTENT-->

app/views/admin/products/multiple_remove.html.erb
<%= @id.inspect %>

app/views/admin/products/new.html.erb
<!-- BEGIN PAGE HEADER-->
<div class="row-fluid">
    <div class="span12"> 
		<!-- BEGIN PAGE TITLE & BREADCRUMB-->     
		<h3 class="page-title"> Products  </h3>
		<ul class="breadcrumb">
		   <li>
      <%= link_to admin_dashboard_index_path, :id => "sample_editable_1_new" do %>
          Home <i class="icon-home"></i>
        <% end %>

    </li>
		</ul>
		 <!-- END PAGE TITLE & BREADCRUMB-->
     </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row-fluid">
    <div class="span12">
         <!-- BEGIN SAMPLE FORM PORTLET-->   
                  <div class="portlet box blue">
                     <div class="portlet-title">
                        <h4><i class="icon-reorder"></i>Add Product</h4>
                        <div class="tools">
                           <a href="javascript:;" class="collapse"></a>
                           <a href="#portlet-config" data-toggle="modal" class="config"></a>
                           <a href="javascript:;" class="reload"></a>
                           <a href="javascript:;" class="remove"></a>
                        </div>
                     </div>
                     <div class="portlet-body form">
                        <%= render 'layouts/admin/admin_alert' %>
                        <%= render 'admin/products/form' %>  
                                                   
                     </div>
                  </div>
                  <!-- END SAMPLE FORM PORTLET-->   
    </div>
</div>
        <!-- END PAGE CONTENT-->

app/views/admin/products/show.html.erb
<!-- BEGIN PAGE HEADER-->
<div class="row-fluid">
    <div class="span12"> 
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->     
        <h3 class="page-title"> Products  </h3>
        <ul class="breadcrumb">
           <li>
      <%= link_to admin_dashboard_index_path, :id => "sample_editable_1_new" do %>
          Home <i class="icon-home"></i>
        <% end %>

    </li>
        </ul>
         <!-- END PAGE TITLE & BREADCRUMB-->
     </div>
</div>
<!-- END PAGE HEADER-->
<div class="row-fluid">
        <div class="span8">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <h4><i class="icon-cogs"></i>Products View</h4>
                    <div class="actions">
                       
                    </div>

                </div>
                <div class="portlet-body">
                   
                    <table class="table table-bordered table-striped">
                        <tbody>
                            
                                                     
                          
                            <tr>
                                <td>Name</td>
                                <td><%= @product.name %></td>

                            </tr>
                             <tr>
                                <td>Attachment</td>
                                <td>
                                    <% if File.extname(@product.p_image) != ".mp3" && File.extname(@product.p_image) != ".epub" %>
                                    <%= image_tag("uploads/products/" + @product.p_image, height: '100', width: '100') %>
                                    <% elsif File.extname(@product.p_image) == ".mp3" %>
                                        <%= render 'product_attachment', product: @product, type: "music", height: "100", width: "100" %>
                                    <% else %>
                                        <%= render 'product_attachment', product: @product, type: "file", height: "100" , width: "50" %>
                                    <% end %>
                                </td>

                            </tr>
                             <tr>
                                <td>Artist</td>
                                <td><%= @product.artist %></td>

                            </tr>
                             <tr>
                                <td>Price</td>
                                <td><%= @product.price %></td>

                            </tr>
                             <tr>
                                <td>Height</td>
                                <td><%= @product.height %></td>

                            </tr>
                             <tr>
                                <td>Weight</td>
                                <td><%= @product.weight %></td>

                            </tr>
                             <tr>
                                <td>Stem</td>
                                <td><%= @product.stem %></td>

                            </tr>
                             <tr>
                                <td>Description</td>
                                <td><%=raw @product.description %></td>

                            </tr>                                                      
                           
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>